management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  metrics:

    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true


  logging:
    level:
      org.springframework.web: DEBUG
